version: '3.8'
services:
  neo4j:
    image: neo4j:5.12.0
    container_name: project-neo4j
    ports:
      - "7474:7474"
      - "7473:7473"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/bacco4321
    healthcheck:
      test: ["CMD", "curl", "-u", "neo4j:bacco4321", "http://localhost:7474"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - neo4j-data:/data
    networks:
      - project_default

networks:
  project_default:
    driver: bridge