version: 2.1

executors:
  kotlin-executor:
    docker:
      - image: cimg/openjdk:17.0
    resource_class: large

jobs:
  setup:
    executor: kotlin-executor
    steps:
      - checkout

      - setup_remote_docker:
          version: default

      - run:
          name: Create initial password file for Neo4j
          command: |
            echo "NEO4J_AUTH=neo4j/bacco4321" > initial-password.env
            ls -l

      - persist_to_workspace:
          root: /home/circleci
          paths:
            - .

  build:
    executor: kotlin-executor
    steps:
      - attach_workspace:
          at: /home/circleci

      - run:
          name: Setup environment
          command: |
            sudo apt-get update
            sudo apt-get install -y lib32stdc++6
            sudo apt-get upgrade

      - run:
          name: Change permissions of gradlew
          command: sudo chmod +x ./gradlew

      - run:
          name: Remove existing properties files
          command: |
            rm -f src/test/resources/application-test.properties
            rm -f src/main/resources/application.properties

      - run:
          name: Ensure properties file exists for tests
          command: |
            if [ ! -f src/test/resources/application-test.properties ]; then
              echo "Creating src/test/resources/application-test.properties"
              mkdir -p src/test/resources
              touch src/test/resources/application-test.properties
            fi

      - run:
          name: Ensure properties file exists for dev
          command: |
            if [ ! -f src/main/resources/application.properties ]; then
              echo "Creating src/main/resources/application.properties"
              mkdir -p src/main/resources
              touch src/main/resources/application.properties
            fi

      - run:
          name: Verify existence of application-test.properties
          command: |
            ls -l src/test/resources/application-test.properties
            ls -l src/main/resources/application.properties

      - run:
          name: Verify application-test.properties
          command: cat src/test/resources/application-test.properties

      - run:
          name: Verify application.properties
          command: cat src/main/resources/application.properties

      - run:
          name: Update application-test.properties
          command: |
            echo "spring.neo4j.uri=bolt://localhost:7687" > src/test/resources/application-test.properties
            echo "spring.neo4j.authentication.username=neo4j" >> src/test/resources/application-test.properties
            echo "spring.neo4j.authentication.password=bacco4321" >> src/test/resources/application-test.properties
            echo "spring.servlet.multipart.max-file-size=20MB" >> src/test/resources/application-test.properties
            echo "spring.servlet.multipart.max-request-size=20MB" >> src/test/resources/application-test.properties
            echo "spring.profiles.active=test" >> src/test/resources/application-test.properties

      - run:
          name: Update application.properties
          command: |
            echo "spring.neo4j.uri=bolt://localhost:7687" > src/main/resources/application.properties
            echo "spring.neo4j.authentication.username=neo4j" >> src/main/resources/application.properties
            echo "spring.neo4j.authentication.password=bacco4321" >> src/main/resources/application.properties
            echo "spring.servlet.multipart.max-file-size=20MB" >> src/main/resources/application.properties
            echo "spring.servlet.multipart.max-request-size=20MB" >> src/main/resources/application.properties
            echo "spring.profiles.active=dev" >> src/main/resources/application.properties

      - run:
          name: Verify application-test.properties
          command: cat src/test/resources/application-test.properties

      - run:
          name: Verify application.properties
          command: cat src/main/resources/application.properties

      - run:
          name: List files before compile
          command: ls -R src/

      - run:
          name: Compile the project
          command: ./gradlew compileKotlin

      - persist_to_workspace:
          root: /home/circleci
          paths:
            - .

  test:
    executor: kotlin-executor
    steps:
      - attach_workspace:
          at: /home/circleci

      - setup_remote_docker:
          version: 20.10.7

      - run:
          name: Start Neo4j with Docker Compose
          command: sudo docker-compose -f docker-compose.yml up -d neo4j

      - run:
          name: Wait for Neo4j to be fully up and running
          command: |
            echo "Waiting for Neo4j to be fully up and running..."
            for i in {1..40}; do
              if curl -s -u neo4j:bacco4321 http://localhost:7474; then
                echo "Neo4j is up and running."
                break
              fi
              echo "Waiting... $i"
              sleep 10
            done
            sudo docker-compose -f docker-compose.yml logs neo4j

      - run:
          name: Check Docker Compose services status
          command: |
            sudo docker-compose -f docker-compose.yml ps

      - run:
          name: Docker compose inspect
          command: |
            sudo docker ps
            sudo docker-compose ps

      - run:
          name: Inspect Neo4j
          command: |
            sudo mkdir -p /var/lib/apt/lists/partial
            sudo chmod 755 /var/lib/apt/lists/partial
            echo "docker logs:"
            sudo docker-compose -f docker-compose.yml logs neo4j
            echo "======================================================="
            echo "docker inspect:"
            echo "======================================================="
            NEO4J_CONTAINER_ID=$(docker-compose -f docker-compose.yml ps -q neo4j)
            sudo docker inspect $NEO4J_CONTAINER_ID
            echo "======================================================="
            echo "docker ps:"
            echo "======================================================="
            sudo docker ps
            echo "======================================================="

      - run:
          name: Inspect Neo4j 2
          command: |
            echo "======================================================="
            echo "docker exec"
            echo "======================================================="     
            sudo docker exec -it project-neo4j-1 bash
            sudo curl -u neo4j:bacco4321 http://localhost:7474

      - run:
          name: Verify Neo4j connectivity from host
          command: curl -u neo4j:bacco4321 http://localhost:7687

      - run:
          name: Verify Neo4j connectivity from host
          command: curl -u neo4j:bacco4321 http://localhost:7474

      - run:
          name: List files after compile
          command: ls -R build/

      - run:
          name: Run tests with detailed logging
          command: |
            sudo ./gradlew build test --scan --warning-mode all

      - store_artifacts:
          path: build/reports/tests/test
          destination: test-reports

workflows:
  version: 2
  build-and-test:
    jobs:
      - setup
      - build:
          requires:
            - setup
      - test:
          requires:
            - build
