version: 2.1

executors:
  java-executor:
    docker:
      - image: circleci/openjdk:17-jdk  # Imagen válida de OpenJDK provista por CircleCI
    working_directory: ~/repo

jobs:
  setup-db:
    executor: java-executor
    steps:
      - setup_remote_docker:  # Habilitar Docker
          version: 20.10.7
      - run:
          name: Start Neo4j
          command: |
            docker run -d --name neo4j -p 7687:7687 -e NEO4J_AUTH=neo4j/bacco4321 neo4j:latest
      - run:
          name: Wait for Neo4j
          command: sleep 20  # Esperar a que Neo4j esté completamente en ejecución

  build:
    executor: java-executor
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: ./gradlew dependencies
      - run:
          name: Build project
          command: ./gradlew build

  test:
    executor: java-executor
    steps:
      - checkout
      - run:
          name: Copy Neo4j config
          command: echo "spring.neo4j.uri=bolt://localhost:7687" >> src/main/resources/application-test.properties
      - run:
          name: Wait for Neo4j
          command: sleep 20  # Asegurarse de que Neo4j esté listo antes de ejecutar las pruebas
      - run:
          name: Run tests
          command: ./gradlew test

workflows:
  version: 2
  build-and-test:
    jobs:
      - setup-db
      - build:
          requires:
            - setup-db
      - test:
          requires:
            - build
