version: 2.1

executors:
  kotlin-executor:
    docker:
      - image: cimg/openjdk:17.0

jobs:
  build-and-test:
    executor: kotlin-executor
    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.7

      - run:
          name: Start Neo4j Dev
          command: |
            docker run -d --name neo4j-dev -p 7687:7687 -e NEO4J_AUTH=neo4j/devpassword neo4j:5.18.1

      - run:
          name: Start Neo4j Test
          command: |
            docker run -d --name neo4j-test -p 7688:7687 -e NEO4J_AUTH=neo4j/testpassword neo4j:5.18.1

      - run:
          name: Wait for Neo4j Dev to be fully up and running
          command: |
            echo "Waiting for Neo4j Dev to be fully up and running..."
            for i in {1..120}; do
              if docker exec neo4j-dev curl -s http://localhost:7474/browser/; then
                echo "Neo4j Dev is up and running."
                break
              fi
              echo "Waiting..."
              sleep 5
            done
            docker logs neo4j-dev

      - run:
          name: Wait for Neo4j Test to be fully up and running
          command: |
            echo "Waiting for Neo4j Test to be fully up and running..."
            for i in {1..120}; do
              if docker exec neo4j-test curl -s http://localhost:7474/browser/; then
                echo "Neo4j Test is up and running."
                break
              fi
              echo "Waiting..."
              sleep 5
            done
            docker logs neo4j-test

      - run:
          name: Check Neo4j Dev logs
          command: docker logs neo4j-dev | grep "Remote interface available at"

      - run:
          name: Check Neo4j Test logs
          command: docker logs neo4j-test | grep "Remote interface available at"

      - run:
          name: Setup environment
          command: |
            sudo apt-get update
            sudo apt-get install -y lib32stdc++6

      - run:
          name: Change permissions of gradlew
          command: sudo chmod +x ./gradlew

      - run:
          name: Ensure properties file exists
          command: |
            if [ ! -f src/test/resources/application-test.properties ]; then
              echo "Creating src/test/resources/application-test.properties"
              mkdir -p src/test/resources
              touch src/test/resources/application-test.properties
            fi

      - run:
          name: Update application-test.properties
          command: |
            echo "spring.neo4j.uri=bolt://localhost:7688" > src/test/resources/application-test.properties
            echo "spring.neo4j.authentication.username=neo4j" >> src/test/resources/application-test.properties
            echo "spring.neo4j.authentication.password=testpassword" >> src/test/resources/application-test.properties
            echo "spring.servlet.multipart.max-file-size=20MB" >> src/test/resources/application-test.properties
            echo "spring.servlet.multipart.max-request-size=20MB" >> src/test/resources/application-test.properties
            echo "spring.profiles.active=test" >> src/test/resources/application-test.properties

      - run:
          name: Update application-dev.properties
          command: |
            echo "spring.neo4j.uri=bolt://localhost:7687" > src/main/resources/application-dev.properties
            echo "spring.neo4j.authentication.username=neo4j" >> src/main/resources/application-dev.properties
            echo "spring.neo4j.authentication.password=devpassword" >> src/main/resources/application-dev.properties
            echo "spring.servlet.multipart.max-file-size=20MB" >> src/main/resources/application-dev.properties
            echo "spring.servlet.multipart.max-request-size=20MB" >> src/main/resources/application-dev.properties
            echo "spring.profiles.active=dev" >> src/main/resources/application-dev.properties

      - run:
          name: Run tests with detailed logging
          command: |
            ./gradlew test --warning-mode all \
              --info --debug \
              -Dorg.slf4j.simple.SimpleLogger.LEVEL=DEBUG \
              -Dorg.springframework.core.log.LogMessage.LEVEL_TRACE

      - store_artifacts:
          path: build/reports/tests/test
          destination: test-reports

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
