version: 2.1

executors:
  kotlin-executor:
    docker:
      - image: cimg/openjdk:17.0 # Use an appropriate JDK version

jobs:
  build-and-test:
    executor: kotlin-executor
    steps:
      - setup_remote_docker:
          version: 20.10.7
      - checkout # Checkout the code from your repository
      - run:
          name: Pull Neo4j image
          command: docker pull neo4j:latest
      - run:
          name: Start Neo4j
          command: |
            docker run -d --name neo4j -p 7687:7687 -e NEO4J_AUTH=neo4j/bacco4321 neo4j:latest
      - run:
          name: Wait for Neo4j
          command: |
            echo "Waiting for Neo4j to be fully up and running..."
            for i in {1..30}; do
              nc -zv localhost 7687 && break
              echo "Waiting..."
              sleep 5
            done
            docker logs neo4j
      - run:
          name: Setup environment
          command: |
            sudo apt-get update
            sudo apt-get install -y lib32stdc++6
      - run:
          name: Change permissions of gradlew
          command: sudo chmod +x ./gradlew
      - run:
          name: Check Neo4j logs
          command: docker logs neo4j | grep "Remote interface available at"
      - run:
          name: Copy Neo4j config
          command: echo "spring.neo4j.uri=bolt://localhost:7687" >> src/test/resources/application-test.properties
      - run:
          name: Build and Test
          command: ./gradlew clean build
      - run:
          name: Run tests
          command: ./gradlew test
      - store_artifacts:
          path: app/build/reports/tests # Adjust the path to your test reports
          destination: test-reports

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
